version: "3.9"
   
services:
  backend:
    build: 
      context: ./django-backend-docker
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - staticfiles:/backend/staticfiles
  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    volumes:
      - staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  mysql_volume:
  staticfiles:
