# Generated by Django 3.2.9 on 2021-11-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('max_phase', models.IntegerField()),
                ('structure', models.CharField(max_length=4000)),
                ('inchi_key', models.CharField(max_length=27, unique=True)),
            ],
            options={
                'db_table': 'molecule',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('organism', models.TextField()),
            ],
            options={
                'db_table': 'target',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
                ('units', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('relation', models.CharField(max_length=2)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='molecules.molecule')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='molecules.target')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
