# Generated by Django 3.2.9 on 2021-11-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='molecules.molecule'),
        ),
    ]
